name:                development
version:             0.1.0.0
github:              "jasonsychau/graphql-w-persistent"
license:             BSD3
author:              "Jason Chau"
maintainer:          "jasonsychau@live.ca"
copyright:           "2019 Jason Chau"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- json
- containers
- text
- persistent-postgresql
- persistent-template
- conduit

library:
  source-dirs: src

tests:
  development-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - development
